/**
 * metric.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiWorkflow } from './apiWorkflow';


export interface ApiListWorkflowsResponse { 
    count?: number;
    workflows?: Array<ApiWorkflow>;
    page?: number;
    pages?: number;
    totalCount?: number;
}

