/**
 * metric.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiWorkflowExecutionParameter } from './apiWorkflowExecutionParameter';
import { ApiWorkflowTemplate } from './apiWorkflowTemplate';


export interface ApiWorkflowExecution { 
    createdAt?: string;
    uid?: string;
    name?: string;
    phase?: string;
    startedAt?: string;
    finishedAt?: string;
    manifest?: string;
    parameters?: Array<ApiWorkflowExecutionParameter>;
    workflowTemplate?: ApiWorkflowTemplate;
}

