/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 0.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelFile { 
    path?: string;
    name?: string;
    extension?: string;
    size?: string;
    contentType?: string;
    lastModified?: string;
    directory?: boolean;
}

