/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodePool } from './nodePool';


export interface GetConfigResponse { 
    apiUrl?: string;
    domain?: string;
    fqdn?: string;
    nodePool?: NodePool;
}

