/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InferenceServiceCondition } from './inferenceServiceCondition';


export interface GetInferenceServiceResponse { 
    ready?: boolean;
    conditions?: Array<InferenceServiceCondition>;
    predictUrl?: string;
}

