/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 0.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowExecutionStatisticReport } from './workflowExecutionStatisticReport';


export interface GetWorkflowExecutionStatisticsForNamespaceResponse { 
    stats?: WorkflowExecutionStatisticReport;
}

