/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 0.19.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoogleProtobufAny } from './googleProtobufAny';


export interface GoogleRpcStatus { 
    code?: number;
    message?: string;
    details?: Array<GoogleProtobufAny>;
}

