/**
 * metric.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoogleProtobufAny } from './googleProtobufAny';


export interface GrpcGatewayRuntimeStreamError { 
    grpcCode?: number;
    httpCode?: number;
    message?: string;
    httpStatus?: string;
    details?: Array<GoogleProtobufAny>;
}

