/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListFilesResponse { 
    count?: number;
    totalCount?: number;
    page?: number;
    pages?: number;
    files?: Array<any>;
    parentPath?: string;
}

