/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceTemplate } from './workspaceTemplate';


export interface ListWorkspaceTemplatesResponse { 
    count?: number;
    workspaceTemplates?: Array<WorkspaceTemplate>;
    page?: number;
    pages?: number;
    totalCount?: number;
}

