/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoogleRpcStatus } from './googleRpcStatus';
import { LogStreamResponse } from './logStreamResponse';


export interface StreamResultOfLogStreamResponse { 
    result?: LogStreamResponse;
    error?: GoogleRpcStatus;
}

