/**
 * Onepanel
 * Onepanel API
 *
 * The version of the OpenAPI document: 0.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowExecutionStatisticReport { 
    total?: number;
    lastExecuted?: string;
    running?: number;
    completed?: number;
    failed?: number;
    terminated?: number;
}

