/**
 * workflow.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowExecutionParameter } from './workflowExecutionParameter';
import { WorkflowTemplate } from './workflowTemplate';


export interface WorkflowExecution { 
    createdAt?: string;
    uid?: string;
    name?: string;
    phase?: string;
    startedAt?: string;
    finishedAt?: string;
    manifest?: string;
    parameters?: Array<WorkflowExecutionParameter>;
    workflowTemplate?: WorkflowTemplate;
}

