export * from './authService.service';
import { AuthServiceService } from './authService.service';
export * from './configService.service';
import { ConfigServiceService } from './configService.service';
export * from './cronWorkflowService.service';
import { CronWorkflowServiceService } from './cronWorkflowService.service';
export * from './fileService.service';
import { FileServiceService } from './fileService.service';
export * from './labelService.service';
import { LabelServiceService } from './labelService.service';
export * from './namespaceService.service';
import { NamespaceServiceService } from './namespaceService.service';
export * from './secretService.service';
import { SecretServiceService } from './secretService.service';
export * from './serviceService.service';
import { ServiceServiceService } from './serviceService.service';
export * from './workflowService.service';
import { WorkflowServiceService } from './workflowService.service';
export * from './workflowTemplateService.service';
import { WorkflowTemplateServiceService } from './workflowTemplateService.service';
export * from './workspaceService.service';
import { WorkspaceServiceService } from './workspaceService.service';
export * from './workspaceTemplateService.service';
import { WorkspaceTemplateServiceService } from './workspaceTemplateService.service';
export const APIS = [AuthServiceService, ConfigServiceService, CronWorkflowServiceService, FileServiceService, LabelServiceService, NamespaceServiceService, SecretServiceService, ServiceServiceService, WorkflowServiceService, WorkflowTemplateServiceService, WorkspaceServiceService, WorkspaceTemplateServiceService];
